// GENERATED by tool/gen_tokens.dart from design/tokens.json. Do not edit.
// Run `dart run tool/gen_tokens.dart` after changing the tokens.

import 'package:flutter/painting.dart';

import 'colors.dart';

const paperLight = EndlessColors(
  text: Color(0xFF1E1C19),
  textMuted: Color(0xFF5E574C),
  textFaint: Color(0xFF8A8274),
  surface: Color(0xFFFFFDF8),
  surfaceSunk: Color(0xFFFBF8F1),
  bg: Color(0xFFF6F1E7),
  side: Color(0xFFEEE7D8),
  line: Color(0xFFDDD4C2),
  lineStrong: Color(0xFFCFC5B1),
  lineSoft: Color(0xFFEAE3D5),
  dot: Color(0xFFD6CDBA),
  inverse: Color(0xFF1E1C19),
  inverseRaised: Color(0xFF3D3830),
  onInverse: Color(0xFFFFFDF8),
  accent: Color(0xFF2B5A8C),
  accentHover: Color(0xFF1F4570),
  accentDeep: Color(0xFF214A75),
  accentTint: Color(0xFFE1E9F3),
  clay: Color(0xFFB5532A),
  clayTint: Color(0xFFF6E1D6),
  green: Color(0xFF3E7B4F),
  greenTint: Color(0xFFE3ECE4),
  plum: Color(0xFF7A4E73),
  plumTint: Color(0xFFEDE3EC),
  gold: Color(0xFF8A6400),
  star: Color(0xFFE8B730),
  stickyYellow: Color(0xFFFBEFC4),
  danger: Color(0xFFB3382C),
  spellUnderline: Color(0xFFC23B2E),
  onAccent: Color(0xFFFFFDF8),
  shadow: Color(0x731E1C19),
  menuTile: Color(0xFFF3EEE3),
  clayDeep: Color(0xFF8E4220),
  greenDeep: Color(0xFF2F5D3A),
  sideSelected: Color(0xFFE0D6C2),
  lineDashed: Color(0xFFBFB49E),
  accentWash: Color(0xFFEEF3F8),
  switchOff: Color(0xFFB8AE9B),
  warningTint: Color(0xFFF6E6D8),
  onWarning: Color(0xFF5A2A12),
  goldDeep: Color(0xFF5A4000),
  moss: Color(0xFF4E7A52),
  paperLine: Color(0xFFC9D6E3),
  paperGrid: Color(0xFFD6DEE8),
  paperMargin: Color(0x80C45446),
  scrim: Color(0x6B1E1C19),
  frost: Color(0x8CF6F1E7),
  laserRed: Color(0xFFE0312B),
  laserGreen: Color(0xFF2E9E4F),
  laserBlue: Color(0xFF2F6FD6),
  scribbleMark: Color(0xFFC44A3C),
  onStar: Color(0xFF1E1C19),
);

const paperDark = EndlessColors(
  text: Color(0xFFEEE8DC),
  textMuted: Color(0xFFADA493),
  textFaint: Color(0xFF8A8274),
  surface: Color(0xFF2A2723),
  surfaceSunk: Color(0xFF34302A),
  bg: Color(0xFF1C1A17),
  side: Color(0xFF24211D),
  line: Color(0xFF3B3731),
  lineStrong: Color(0xFF5A544A),
  lineSoft: Color(0xFF34302A),
  dot: Color(0xFF3A352E),
  inverse: Color(0xFFEEE8DC),
  inverseRaised: Color(0xFFD6CFC1),
  onInverse: Color(0xFF1C1A17),
  accent: Color(0xFF86AEDB),
  accentHover: Color(0xFFA9C6E6),
  accentDeep: Color(0xFFA9C6E6),
  accentTint: Color(0xFF2C3847),
  onAccent: Color(0xFF111111),
  clay: Color(0xFFE6946A),
  clayTint: Color(0xFF4A3025),
  green: Color(0xFF8CCB9A),
  greenTint: Color(0xFF26352A),
  plum: Color(0xFFD7A2CE),
  plumTint: Color(0xFF3D2C3A),
  gold: Color(0xFFE8B730),
  star: Color(0xFFE8B730),
  stickyYellow: Color(0xFF5C5130),
  danger: Color(0xFFE07A6E),
  spellUnderline: Color(0xFFE07A6E),
  shadow: Color(0xB3000000),
  menuTile: Color(0xFF34302A),
  clayDeep: Color(0xFFF0B090),
  greenDeep: Color(0xFFA8D8B2),
  sideSelected: Color(0xFF3A352F),
  lineDashed: Color(0xFF5A544A),
  accentWash: Color(0xFF26303C),
  switchOff: Color(0xFF5A544A),
  warningTint: Color(0xFF3F2A1F),
  onWarning: Color(0xFFF0C2A8),
  goldDeep: Color(0xFFF3DE9A),
  moss: Color(0xFF9CC4A0),
  paperLine: Color(0xFF33414F),
  paperGrid: Color(0xFF2E3842),
  paperMargin: Color(0x80E07A6E),
  scrim: Color(0x99000000),
  frost: Color(0x8C1C1A17),
  laserRed: Color(0xFFFF5A4F),
  laserGreen: Color(0xFF4CC46E),
  laserBlue: Color(0xFF5B93F0),
  scribbleMark: Color(0xFFE07A6E),
  onStar: Color(0xFF1E1C19),
);

const inkDefaults = <Color>[
  Color(0xFF1E1C19),
  Color(0xFF2B5A8C),
  Color(0xFFB5532A),
];

const extraInkDefaults = <Color>[
  Color(0xFF3E7B4F),
  Color(0xFFB83A3A),
  Color(0xFF7A4E73),
  Color(0xFFD9A21B),
  Color(0xFF3B82C4),
  Color(0xFF8A8378),
];

const extraInkAddable = <Color>[
  Color(0xFF1F6B75),
  Color(0xFFC4577A),
  Color(0xFF7A5A3A),
  Color(0xFF6F8F2A),
];

const extraInkMax = 10;

/// Notebook spine and folder colors (stored colors; dark mode brightens them like ink).
const coverColors = <Color>[
  Color(0xFF2B5A8C),
  Color(0xFFB5532A),
  Color(0xFF4E7A52),
  Color(0xFF7A4E73),
  Color(0xFF1F6B75),
  Color(0xFF8A6400),
];

/// Ink color shown in dark mode, keyed by the stored (light) color.
const inkDisplayDark = <int, Color>{
  0xFF1E1C19: Color(0xFFEEE8DC),
  0xFF2B5A8C: Color(0xFF86AEDB),
  0xFFB5532A: Color(0xFFE6946A),
  0xFF3E7B4F: Color(0xFF8CCB9A),
  0xFF7A4E73: Color(0xFFD7A2CE),
  0xFF1F6B75: Color(0xFF7CC6CF),
  0xFF8A6400: Color(0xFFE8B730),
  0xFFA2445A: Color(0xFFE394A7),
  0xFF4E7A52: Color(0xFF9CC4A0),
};

/// The 8 accent choices (light, dark). The first one is the theme default.
const accents = <String, (Color, Color)>{
  'blue': (Color(0xFF2B5A8C), Color(0xFF86AEDB)),
  'terracotta': (Color(0xFFB5532A), Color(0xFFE6946A)),
  'green': (Color(0xFF3E7B4F), Color(0xFF8CCB9A)),
  'plum': (Color(0xFF7A4E73), Color(0xFFD7A2CE)),
  'teal': (Color(0xFF1F6B75), Color(0xFF7CC6CF)),
  'gold': (Color(0xFF8A6400), Color(0xFFE8B730)),
  'rose': (Color(0xFFA2445A), Color(0xFFE394A7)),
};

/// Theme swatches for the Themes screen: (light, dark).
const themeSwatches = <String, (ThemeSwatch, ThemeSwatch)>{
  'paper': (ThemeSwatch(bg: Color(0xFFF6F1E7), side: Color(0xFFEEE7D8), surface: Color(0xFFFFFDF8), line: Color(0xFFDDD4C2), text: Color(0xFF1E1C19), dot: Color(0xFFD6CDBA), accent: Color(0xFF2B5A8C)), ThemeSwatch(bg: Color(0xFF1C1A17), side: Color(0xFF24211D), surface: Color(0xFF2A2723), line: Color(0xFF3B3731), text: Color(0xFFEEE8DC), dot: Color(0xFF3A352E), accent: Color(0xFF86AEDB))),
  'midnight': (ThemeSwatch(bg: Color(0xFFEEF1F5), side: Color(0xFFE3E8EF), surface: Color(0xFFFFFFFF), line: Color(0xFFD3DAE4), text: Color(0xFF151A22), dot: Color(0xFFC9D1DC), accent: Color(0xFF3A5BA0)), ThemeSwatch(bg: Color(0xFF11151C), side: Color(0xFF171C25), surface: Color(0xFF1D2330), line: Color(0xFF2C3445), text: Color(0xFFE6EBF2), dot: Color(0xFF283042), accent: Color(0xFF8FB0F0))),
  'sage': (ThemeSwatch(bg: Color(0xFFEFF2EA), side: Color(0xFFE4E9DC), surface: Color(0xFFFBFCF8), line: Color(0xFFD2D9C6), text: Color(0xFF1B2118), dot: Color(0xFFC8D1BA), accent: Color(0xFF3E6B45)), ThemeSwatch(bg: Color(0xFF151A14), side: Color(0xFF1B2119), surface: Color(0xFF21281F), line: Color(0xFF313B2E), text: Color(0xFFE5EBDF), dot: Color(0xFF2B3428), accent: Color(0xFF8FC096))),
  'blush': (ThemeSwatch(bg: Color(0xFFF8EFEE), side: Color(0xFFF0E3E1), surface: Color(0xFFFFFBFA), line: Color(0xFFE6D2CF), text: Color(0xFF231918), dot: Color(0xFFE0C9C5), accent: Color(0xFFA2445A)), ThemeSwatch(bg: Color(0xFF1C1415), side: Color(0xFF241A1B), surface: Color(0xFF2B2021), line: Color(0xFF3E2F30), text: Color(0xFFF1E4E3), dot: Color(0xFF3A2B2C), accent: Color(0xFFE394A7))),
  'graphite': (ThemeSwatch(bg: Color(0xFFF2F2F0), side: Color(0xFFE8E8E5), surface: Color(0xFFFFFFFF), line: Color(0xFFD6D6D2), text: Color(0xFF19191A), dot: Color(0xFFCFCFCB), accent: Color(0xFF2F3B52)), ThemeSwatch(bg: Color(0xFF121213), side: Color(0xFF19191B), surface: Color(0xFF202022), line: Color(0xFF333336), text: Color(0xFFEDEDEE), dot: Color(0xFF2D2D30), accent: Color(0xFFC9D3E6))),
  'contrast': (ThemeSwatch(bg: Color(0xFFFFFFFF), side: Color(0xFFF0F0F0), surface: Color(0xFFFFFFFF), line: Color(0xFF000000), text: Color(0xFF000000), dot: Color(0xFFBDBDBD), accent: Color(0xFF0040C0)), ThemeSwatch(bg: Color(0xFF000000), side: Color(0xFF0A0A0A), surface: Color(0xFF000000), line: Color(0xFFFFFFFF), text: Color(0xFFFFFFFF), dot: Color(0xFF4A4A4A), accent: Color(0xFFFFD400))),
  'harbor': (ThemeSwatch(bg: Color(0xFFEDF3F4), side: Color(0xFFE1EBEC), surface: Color(0xFFFAFDFD), line: Color(0xFFCFDDDF), text: Color(0xFF122024), dot: Color(0xFFC3D4D7), accent: Color(0xFF1F6B75)), ThemeSwatch(bg: Color(0xFF0F181A), side: Color(0xFF152124), surface: Color(0xFF1B2A2D), line: Color(0xFF2A3D41), text: Color(0xFFE1EDEF), dot: Color(0xFF243538), accent: Color(0xFF7CC6CF))),
};

abstract final class Radii {
  static const double chip = 999.0;
  static const double pill = 16.0;
  static const double card = 14.0;
  static const double button = 12.0;
  static const double key = 10.0;
  static const double small = 8.0;
  static const double dialog = 18.0;
}

abstract final class Sizes {
  static const double touchTarget = 44.0;
  static const double toolbarHeight = 52.0;
  static const Size tabletFrame = Size(1280.0, 800.0);
  static const double paperDotSpacing = 26.0;
  static const double paperDotRadius = 1.3;
}

abstract final class FontFamilies {
  static const ui = 'Figtree';
  static const serif = 'Newsreader';
  static const handwritingSample = 'Caveat';
}

/// Type scale. Text case (e.g. uppercase section labels) is applied by the widget.
abstract final class TypeScale {
  static const pillTitle = TextStyle(fontFamily: 'Figtree', fontSize: 16.0, fontWeight: FontWeight.w600);
  static const pillSub = TextStyle(fontFamily: 'Figtree', fontSize: 13.0, fontWeight: FontWeight.w400);
  static const button = TextStyle(fontFamily: 'Figtree', fontSize: 14.0, fontWeight: FontWeight.w600);
  static const sectionLabel = TextStyle(fontFamily: 'Figtree', fontSize: 12.0, fontWeight: FontWeight.w600, letterSpacing: 0.96);
  static const panelTitle = TextStyle(fontFamily: 'Newsreader', fontSize: 24.0, fontWeight: FontWeight.w400);
  static const pageHeading = TextStyle(fontFamily: 'Newsreader', fontSize: 34.0, fontWeight: FontWeight.w400);
}
